# Setup
title:               Welcome to Sungju Pages
tagline:             'sungju'
description:         'Sungju pages'
url:                 https://sungju.org/
baseurl:             'https://sungju.github.io'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Sungju Kwon
  url:               https://sungju.org/

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
