# Setup
title:               Welcome to Sungju's Pages
tagline:             'sungju'
description:         'Sungju pages'
url:                 https://sungju.org/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Sungju Kwon
  url:               https://sungju.org/

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
